version: "3.8"

services:
  kawa-customers-db:
    image: mysql:latest
    environment:
      MYSQL_USER: customers
      MYSQL_PASSWORD: kawacustomers
      MYSQL_DATABASE: customer_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306" 
    expose:
      - "3306"
    volumes:
      - customers-data:/var/lib/mysql
      - ./database/scripts:/docker-entrypoint-initdb.d
    networks:
      - kawa-customers-network
      - kawa-shared-network

  kawa-customers-app:
    container_name: kawa_customers
    build:
      context: .
    ports:
      - "8082:82"
    depends_on:
      - kawa-customers-db
    environment:
      - DATABASE_URL=mysql+mysqlconnector://customers:kawacustomers@kawa-customers-db:3306/customer_db
    networks:
      - kawa-customers-network
      - kawa-shared-network

volumes:
  customers-data:

networks:
  kawa-customers-network:
  kawa-shared-network:
    external: true